---
title: "ESM 244 Lab 1"
author: "Grace Kumaishi"
date: "1/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in SF trees data

```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))
```

### Basic wrangling reminders

Refresh some skills for data wrangling & summary statistics using functions in the `dplyr` package. 

Find the top five highest observations of trees by legal_status, do some wrangling, make a graph. 

```{r}
top_5_status <- sf_trees %>% 
  count(legal_status) %>% #recognizes groups, finds counts, and puts in a nice table (groupby, summarize, n all in one!)
  drop_na(legal_status) %>% 
  rename(tree_count = n) %>% 
  relocate(tree_count) %>% #in dplyr, moves variables around, in this case we relocated tree_count to the first column position
  slice_max(tree_count, n = 5) #allows you to identify the rows with the highest values for a variable that you specify and only keeps the top number that you want
```







